name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Set a branch to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and auto-lastmod

      - name: Create commit_hash.txt
        run: git rev-parse HEAD > commit_hash.txt

      - name: Create build_date.txt
        run: date -u +"%Y%m%d%H%M%S" > build_date.txt

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './' # The directory containing your static files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4